# CMake generated Testfile for 
# Source directory: /home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/xobjdetect
# Build directory: /home/nerdstar/NerdStar/backend/opencv/opencv_build/modules/xobjdetect
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_xobjdetect "/home/nerdstar/NerdStar/backend/opencv/opencv_build/bin/opencv_test_xobjdetect" "--gtest_output=xml:opencv_test_xobjdetect.xml")
set_tests_properties(opencv_test_xobjdetect PROPERTIES  LABELS "Extra;opencv_xobjdetect;Accuracy" WORKING_DIRECTORY "/home/nerdstar/NerdStar/backend/opencv/opencv_build/test-reports/accuracy" _BACKTRACE_TRIPLES "/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVUtils.cmake;1765;add_test;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1364;ocv_add_test_from_target;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1122;ocv_add_accuracy_tests;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/xobjdetect/CMakeLists.txt;2;ocv_define_module;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/xobjdetect/CMakeLists.txt;0;")
add_test(opencv_perf_xobjdetect "/home/nerdstar/NerdStar/backend/opencv/opencv_build/bin/opencv_perf_xobjdetect" "--gtest_output=xml:opencv_perf_xobjdetect.xml")
set_tests_properties(opencv_perf_xobjdetect PROPERTIES  LABELS "Extra;opencv_xobjdetect;Performance" WORKING_DIRECTORY "/home/nerdstar/NerdStar/backend/opencv/opencv_build/test-reports/performance" _BACKTRACE_TRIPLES "/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVUtils.cmake;1765;add_test;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1263;ocv_add_test_from_target;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1123;ocv_add_perf_tests;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/xobjdetect/CMakeLists.txt;2;ocv_define_module;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/xobjdetect/CMakeLists.txt;0;")
add_test(opencv_sanity_xobjdetect "/home/nerdstar/NerdStar/backend/opencv/opencv_build/bin/opencv_perf_xobjdetect" "--gtest_output=xml:opencv_perf_xobjdetect.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_xobjdetect PROPERTIES  LABELS "Extra;opencv_xobjdetect;Sanity" WORKING_DIRECTORY "/home/nerdstar/NerdStar/backend/opencv/opencv_build/test-reports/sanity" _BACKTRACE_TRIPLES "/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVUtils.cmake;1765;add_test;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1264;ocv_add_test_from_target;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1123;ocv_add_perf_tests;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/xobjdetect/CMakeLists.txt;2;ocv_define_module;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/xobjdetect/CMakeLists.txt;0;")
subdirs("tools")
subdirs("data")
