# CMake generated Testfile for 
# Source directory: /home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudabgsegm
# Build directory: /home/nerdstar/NerdStar/backend/opencv/opencv_build/modules/cudabgsegm
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_cudabgsegm "/home/nerdstar/NerdStar/backend/opencv/opencv_build/bin/opencv_test_cudabgsegm" "--gtest_output=xml:opencv_test_cudabgsegm.xml")
set_tests_properties(opencv_test_cudabgsegm PROPERTIES  LABELS "Extra;opencv_cudabgsegm;Accuracy" WORKING_DIRECTORY "/home/nerdstar/NerdStar/backend/opencv/opencv_build/test-reports/accuracy" _BACKTRACE_TRIPLES "/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVUtils.cmake;1765;add_test;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1364;ocv_add_test_from_target;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1122;ocv_add_accuracy_tests;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudabgsegm/CMakeLists.txt;9;ocv_define_module;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudabgsegm/CMakeLists.txt;0;")
add_test(opencv_perf_cudabgsegm "/home/nerdstar/NerdStar/backend/opencv/opencv_build/bin/opencv_perf_cudabgsegm" "--gtest_output=xml:opencv_perf_cudabgsegm.xml")
set_tests_properties(opencv_perf_cudabgsegm PROPERTIES  LABELS "Extra;opencv_cudabgsegm;Performance" WORKING_DIRECTORY "/home/nerdstar/NerdStar/backend/opencv/opencv_build/test-reports/performance" _BACKTRACE_TRIPLES "/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVUtils.cmake;1765;add_test;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1263;ocv_add_test_from_target;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1123;ocv_add_perf_tests;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudabgsegm/CMakeLists.txt;9;ocv_define_module;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudabgsegm/CMakeLists.txt;0;")
add_test(opencv_sanity_cudabgsegm "/home/nerdstar/NerdStar/backend/opencv/opencv_build/bin/opencv_perf_cudabgsegm" "--gtest_output=xml:opencv_perf_cudabgsegm.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_cudabgsegm PROPERTIES  LABELS "Extra;opencv_cudabgsegm;Sanity" WORKING_DIRECTORY "/home/nerdstar/NerdStar/backend/opencv/opencv_build/test-reports/sanity" _BACKTRACE_TRIPLES "/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVUtils.cmake;1765;add_test;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1264;ocv_add_test_from_target;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1123;ocv_add_perf_tests;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudabgsegm/CMakeLists.txt;9;ocv_define_module;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudabgsegm/CMakeLists.txt;0;")
