# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...4.1)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS opencv_cudev opencv_core opencv_cudaarithm opencv_flann opencv_geometry opencv_hdf opencv_imgproc opencv_intensity_transform opencv_ml opencv_phase_unwrapping opencv_plot opencv_ptcloud opencv_quality opencv_rapid opencv_reg opencv_rgbd opencv_shape opencv_signal opencv_stereo opencv_surface_matching opencv_alphamat opencv_cudafilters opencv_cudaimgproc opencv_cudastereo opencv_cudawarping opencv_dnn opencv_dnn_superres opencv_features opencv_freetype opencv_fuzzy opencv_hfs opencv_img_hash opencv_imgcodecs opencv_line_descriptor opencv_objdetect opencv_photo opencv_saliency opencv_text opencv_video opencv_videoio opencv_wechat_qrcode opencv_xfeatures2d opencv_ximgproc opencv_xobjdetect opencv_xphoto opencv_bgsegm opencv_calib opencv_cudabgsegm opencv_cudacodec opencv_cudafeatures2d opencv_cudalegacy opencv_cudaobjdetect opencv_datasets opencv_face opencv_gapi opencv_highgui opencv_optflow opencv_sfm opencv.sfm.correspondence opencv.sfm.multiview opencv.sfm.numeric opencv_stitching opencv_structured_light opencv_tracking opencv_xstereo opencv_bioinspired opencv_ccalib opencv_cudaoptflow opencv_dnn_objdetect opencv_dpm opencv_superres opencv_videostab)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target opencv_cudev
add_library(opencv_cudev SHARED IMPORTED)

# Create imported target opencv_core
add_library(opencv_core SHARED IMPORTED)

set_target_properties(opencv_core PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_cudev"
)

# Create imported target opencv_cudaarithm
add_library(opencv_cudaarithm SHARED IMPORTED)

set_target_properties(opencv_cudaarithm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudev;opencv_core"
)

# Create imported target opencv_flann
add_library(opencv_flann SHARED IMPORTED)

set_target_properties(opencv_flann PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudev;opencv_core"
)

# Create imported target opencv_geometry
add_library(opencv_geometry SHARED IMPORTED)

set_target_properties(opencv_geometry PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_cudev;opencv_core;opencv_flann"
)

# Create imported target opencv_hdf
add_library(opencv_hdf SHARED IMPORTED)

set_target_properties(opencv_hdf PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudev;opencv_core"
)

# Create imported target opencv_imgproc
add_library(opencv_imgproc SHARED IMPORTED)

set_target_properties(opencv_imgproc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_cudev;opencv_core;opencv_flann;opencv_geometry"
)

# Create imported target opencv_intensity_transform
add_library(opencv_intensity_transform SHARED IMPORTED)

set_target_properties(opencv_intensity_transform PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_ml
add_library(opencv_ml SHARED IMPORTED)

set_target_properties(opencv_ml PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_cudev;opencv_core;opencv_flann;opencv_geometry"
)

# Create imported target opencv_phase_unwrapping
add_library(opencv_phase_unwrapping SHARED IMPORTED)

set_target_properties(opencv_phase_unwrapping PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_plot
add_library(opencv_plot SHARED IMPORTED)

set_target_properties(opencv_plot PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_ptcloud
add_library(opencv_ptcloud SHARED IMPORTED)

set_target_properties(opencv_ptcloud PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_quality
add_library(opencv_quality SHARED IMPORTED)

set_target_properties(opencv_quality PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml"
)

# Create imported target opencv_rapid
add_library(opencv_rapid SHARED IMPORTED)

set_target_properties(opencv_rapid PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_reg
add_library(opencv_reg SHARED IMPORTED)

set_target_properties(opencv_reg PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_rgbd
add_library(opencv_rgbd SHARED IMPORTED)

set_target_properties(opencv_rgbd PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ptcloud;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ptcloud"
)

# Create imported target opencv_shape
add_library(opencv_shape SHARED IMPORTED)

set_target_properties(opencv_shape PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_signal
add_library(opencv_signal SHARED IMPORTED)

set_target_properties(opencv_signal PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudev;opencv_core"
)

# Create imported target opencv_stereo
add_library(opencv_stereo SHARED IMPORTED)

set_target_properties(opencv_stereo PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_surface_matching
add_library(opencv_surface_matching SHARED IMPORTED)

set_target_properties(opencv_surface_matching PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_cudev;opencv_core;opencv_flann"
)

# Create imported target opencv_alphamat
add_library(opencv_alphamat SHARED IMPORTED)

set_target_properties(opencv_alphamat PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_cudafilters
add_library(opencv_cudafilters SHARED IMPORTED)

set_target_properties(opencv_cudafilters PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_cudaimgproc
add_library(opencv_cudaimgproc SHARED IMPORTED)

set_target_properties(opencv_cudaimgproc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters"
)

# Create imported target opencv_cudastereo
add_library(opencv_cudastereo SHARED IMPORTED)

set_target_properties(opencv_cudastereo PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo"
)

# Create imported target opencv_cudawarping
add_library(opencv_cudawarping SHARED IMPORTED)

set_target_properties(opencv_cudawarping PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_dnn
add_library(opencv_dnn SHARED IMPORTED)

set_target_properties(opencv_dnn PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_dnn_superres
add_library(opencv_dnn_superres SHARED IMPORTED)

set_target_properties(opencv_dnn_superres PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_quality;opencv_dnn;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_quality;opencv_dnn"
)

# Create imported target opencv_features
add_library(opencv_features SHARED IMPORTED)

set_target_properties(opencv_features PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn"
)

# Create imported target opencv_freetype
add_library(opencv_freetype SHARED IMPORTED)

set_target_properties(opencv_freetype PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_fuzzy
add_library(opencv_fuzzy SHARED IMPORTED)

set_target_properties(opencv_fuzzy PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_hfs
add_library(opencv_hfs SHARED IMPORTED)

set_target_properties(opencv_hfs PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_img_hash
add_library(opencv_img_hash SHARED IMPORTED)

set_target_properties(opencv_img_hash PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_imgcodecs
add_library(opencv_imgcodecs SHARED IMPORTED)

set_target_properties(opencv_imgcodecs PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc"
)

# Create imported target opencv_line_descriptor
add_library(opencv_line_descriptor SHARED IMPORTED)

set_target_properties(opencv_line_descriptor PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features"
)

# Create imported target opencv_objdetect
add_library(opencv_objdetect SHARED IMPORTED)

set_target_properties(opencv_objdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features"
)

# Create imported target opencv_photo
add_library(opencv_photo SHARED IMPORTED)

set_target_properties(opencv_photo PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc"
)

# Create imported target opencv_saliency
add_library(opencv_saliency SHARED IMPORTED)

set_target_properties(opencv_saliency PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features"
)

# Create imported target opencv_text
add_library(opencv_text SHARED IMPORTED)

set_target_properties(opencv_text PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_dnn;opencv_features;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_dnn;opencv_features"
)

# Create imported target opencv_video
add_library(opencv_video SHARED IMPORTED)

set_target_properties(opencv_video PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features"
)

# Create imported target opencv_videoio
add_library(opencv_videoio SHARED IMPORTED)

set_target_properties(opencv_videoio PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_imgcodecs;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_imgcodecs"
)

# Create imported target opencv_wechat_qrcode
add_library(opencv_wechat_qrcode SHARED IMPORTED)

set_target_properties(opencv_wechat_qrcode PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_objdetect;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_objdetect"
)

# Create imported target opencv_xfeatures2d
add_library(opencv_xfeatures2d SHARED IMPORTED)

set_target_properties(opencv_xfeatures2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_shape;opencv_dnn;opencv_features;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_shape;opencv_dnn;opencv_features"
)

# Create imported target opencv_ximgproc
add_library(opencv_ximgproc SHARED IMPORTED)

set_target_properties(opencv_ximgproc PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_video;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_video"
)

# Create imported target opencv_xobjdetect
add_library(opencv_xobjdetect SHARED IMPORTED)

set_target_properties(opencv_xobjdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_imgcodecs"
)

# Create imported target opencv_xphoto
add_library(opencv_xphoto SHARED IMPORTED)

set_target_properties(opencv_xphoto PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_photo;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_photo"
)

# Create imported target opencv_bgsegm
add_library(opencv_bgsegm SHARED IMPORTED)

set_target_properties(opencv_bgsegm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_video;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_video"
)

# Create imported target opencv_calib
add_library(opencv_calib SHARED IMPORTED)

set_target_properties(opencv_calib PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_dnn;opencv_features;opencv_objdetect;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_dnn;opencv_features;opencv_objdetect"
)

# Create imported target opencv_cudabgsegm
add_library(opencv_cudabgsegm SHARED IMPORTED)

set_target_properties(opencv_cudabgsegm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_video;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_video"
)

# Create imported target opencv_cudacodec
add_library(opencv_cudacodec SHARED IMPORTED)

set_target_properties(opencv_cudacodec PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudawarping;opencv_imgcodecs;opencv_videoio;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudawarping;opencv_imgcodecs;opencv_videoio"
)

# Create imported target opencv_cudafeatures2d
add_library(opencv_cudafeatures2d SHARED IMPORTED)

set_target_properties(opencv_cudafeatures2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters;opencv_cudawarping;opencv_dnn;opencv_features;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters;opencv_cudawarping;opencv_dnn;opencv_features"
)

# Create imported target opencv_cudalegacy
add_library(opencv_cudalegacy SHARED IMPORTED)

set_target_properties(opencv_cudalegacy PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_xobjdetect;opencv_calib;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_xobjdetect;opencv_calib"
)

# Create imported target opencv_cudaobjdetect
add_library(opencv_cudaobjdetect SHARED IMPORTED)

set_target_properties(opencv_cudaobjdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_xobjdetect;opencv_calib;opencv_cudalegacy;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_xobjdetect;opencv_calib;opencv_cudalegacy"
)

# Create imported target opencv_datasets
add_library(opencv_datasets SHARED IMPORTED)

set_target_properties(opencv_datasets PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_text;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_text"
)

# Create imported target opencv_face
add_library(opencv_face SHARED IMPORTED)

set_target_properties(opencv_face PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_photo;opencv_xobjdetect;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_photo;opencv_xobjdetect"
)

# Create imported target opencv_gapi
add_library(opencv_gapi SHARED IMPORTED)

set_target_properties(opencv_gapi PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_dnn;opencv_features;opencv_video;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_dnn;opencv_features;opencv_video"
)

# Create imported target opencv_highgui
add_library(opencv_highgui SHARED IMPORTED)

set_target_properties(opencv_highgui PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
)

# Create imported target opencv_optflow
add_library(opencv_optflow SHARED IMPORTED)

set_target_properties(opencv_optflow PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_video;opencv_ximgproc;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_video;opencv_ximgproc"
)

# Create imported target opencv_sfm
add_library(opencv_sfm SHARED IMPORTED)

set_target_properties(opencv_sfm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_shape;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_xfeatures2d;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_shape;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_xfeatures2d"
)

# Create imported target opencv.sfm.correspondence
add_library(opencv.sfm.correspondence STATIC IMPORTED)

set_target_properties(opencv.sfm.correspondence PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:glog::glog>;\$<LINK_ONLY:opencv.sfm.multiview>;\$<LINK_ONLY:opencv_imgcodecs>;Eigen3::Eigen"
)

# Create imported target opencv.sfm.multiview
add_library(opencv.sfm.multiview STATIC IMPORTED)

set_target_properties(opencv.sfm.multiview PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:glog::glog>;\$<LINK_ONLY:opencv.sfm.numeric>;Eigen3::Eigen"
)

# Create imported target opencv.sfm.numeric
add_library(opencv.sfm.numeric STATIC IMPORTED)

set_target_properties(opencv.sfm.numeric PROPERTIES
  INTERFACE_LINK_LIBRARIES "Eigen3::Eigen"
)

# Create imported target opencv_stitching
add_library(opencv_stitching SHARED IMPORTED)

set_target_properties(opencv_stitching PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_shape;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_xfeatures2d;opencv_xobjdetect;opencv_calib;opencv_cudafeatures2d;opencv_cudalegacy;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_shape;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_xfeatures2d;opencv_xobjdetect;opencv_calib;opencv_cudafeatures2d;opencv_cudalegacy"
)

# Create imported target opencv_structured_light
add_library(opencv_structured_light SHARED IMPORTED)

set_target_properties(opencv_structured_light PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_phase_unwrapping;opencv_stereo;opencv_dnn;opencv_features;opencv_objdetect;opencv_calib;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_phase_unwrapping;opencv_stereo;opencv_dnn;opencv_features;opencv_objdetect;opencv_calib"
)

# Create imported target opencv_tracking
add_library(opencv_tracking SHARED IMPORTED)

set_target_properties(opencv_tracking PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_plot;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_text;opencv_video;opencv_videoio;opencv_datasets;opencv_highgui;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_plot;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_text;opencv_video;opencv_videoio;opencv_datasets;opencv_highgui"
)

# Create imported target opencv_xstereo
add_library(opencv_xstereo SHARED IMPORTED)

set_target_properties(opencv_xstereo PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_plot;opencv_stereo;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_text;opencv_video;opencv_videoio;opencv_datasets;opencv_highgui;opencv_tracking;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_plot;opencv_stereo;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_text;opencv_video;opencv_videoio;opencv_datasets;opencv_highgui;opencv_tracking"
)

# Create imported target opencv_bioinspired
add_library(opencv_bioinspired SHARED IMPORTED)

set_target_properties(opencv_bioinspired PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
)

# Create imported target opencv_ccalib
add_library(opencv_ccalib SHARED IMPORTED)

set_target_properties(opencv_ccalib PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_shape;opencv_stereo;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_videoio;opencv_xfeatures2d;opencv_calib;opencv_highgui;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_ml;opencv_shape;opencv_stereo;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_videoio;opencv_xfeatures2d;opencv_calib;opencv_highgui"
)

# Create imported target opencv_cudaoptflow
add_library(opencv_cudaoptflow SHARED IMPORTED)

set_target_properties(opencv_cudaoptflow PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_ximgproc;opencv_xobjdetect;opencv_calib;opencv_cudafeatures2d;opencv_cudalegacy;opencv_optflow;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_ximgproc;opencv_xobjdetect;opencv_calib;opencv_cudafeatures2d;opencv_cudalegacy;opencv_optflow"
)

# Create imported target opencv_dnn_objdetect
add_library(opencv_dnn_objdetect SHARED IMPORTED)

set_target_properties(opencv_dnn_objdetect PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_imgcodecs;opencv_videoio;opencv_highgui"
)

# Create imported target opencv_dpm
add_library(opencv_dpm SHARED IMPORTED)

set_target_properties(opencv_dpm PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_videoio;opencv_highgui;opencv_cudev;opencv_core;opencv_flann;opencv_geometry;opencv_imgproc;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_videoio;opencv_highgui"
)

# Create imported target opencv_superres
add_library(opencv_superres SHARED IMPORTED)

set_target_properties(opencv_superres PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_videoio;opencv_ximgproc;opencv_xobjdetect;opencv_calib;opencv_cudacodec;opencv_cudafeatures2d;opencv_cudalegacy;opencv_optflow;opencv_cudaoptflow;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_video;opencv_videoio;opencv_ximgproc;opencv_xobjdetect;opencv_calib;opencv_cudacodec;opencv_cudafeatures2d;opencv_cudalegacy;opencv_optflow;opencv_cudaoptflow"
)

# Create imported target opencv_videostab
add_library(opencv_videostab SHARED IMPORTED)

set_target_properties(opencv_videostab PROPERTIES
  INTERFACE_LINK_LIBRARIES "opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_photo;opencv_video;opencv_videoio;opencv_ximgproc;opencv_xobjdetect;opencv_calib;opencv_cudafeatures2d;opencv_cudalegacy;opencv_optflow;opencv_cudaoptflow;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_geometry;opencv_imgproc;opencv_stereo;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_dnn;opencv_features;opencv_imgcodecs;opencv_objdetect;opencv_photo;opencv_video;opencv_videoio;opencv_ximgproc;opencv_xobjdetect;opencv_calib;opencv_cudafeatures2d;opencv_cudalegacy;opencv_optflow;opencv_cudaoptflow"
)

# Import target "opencv_cudev" for configuration "Release"
set_property(TARGET opencv_cudev APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudev PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudev.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudev.so.501"
  )

# Import target "opencv_core" for configuration "Release"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_core.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_core.so.501"
  )

# Import target "opencv_cudaarithm" for configuration "Release"
set_property(TARGET opencv_cudaarithm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaarithm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudaarithm.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudaarithm.so.501"
  )

# Import target "opencv_flann" for configuration "Release"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_flann.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_flann.so.501"
  )

# Import target "opencv_geometry" for configuration "Release"
set_property(TARGET opencv_geometry APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_geometry PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_geometry.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_geometry.so.501"
  )

# Import target "opencv_hdf" for configuration "Release"
set_property(TARGET opencv_hdf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_hdf PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_hdf.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_hdf.so.501"
  )

# Import target "opencv_imgproc" for configuration "Release"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_imgproc.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_imgproc.so.501"
  )

# Import target "opencv_intensity_transform" for configuration "Release"
set_property(TARGET opencv_intensity_transform APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_intensity_transform PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_intensity_transform.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_intensity_transform.so.501"
  )

# Import target "opencv_ml" for configuration "Release"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_ml.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_ml.so.501"
  )

# Import target "opencv_phase_unwrapping" for configuration "Release"
set_property(TARGET opencv_phase_unwrapping APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_phase_unwrapping PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_phase_unwrapping.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_phase_unwrapping.so.501"
  )

# Import target "opencv_plot" for configuration "Release"
set_property(TARGET opencv_plot APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_plot PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_plot.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_plot.so.501"
  )

# Import target "opencv_ptcloud" for configuration "Release"
set_property(TARGET opencv_ptcloud APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ptcloud PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_ptcloud.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_ptcloud.so.501"
  )

# Import target "opencv_quality" for configuration "Release"
set_property(TARGET opencv_quality APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_quality PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_quality.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_quality.so.501"
  )

# Import target "opencv_rapid" for configuration "Release"
set_property(TARGET opencv_rapid APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_rapid PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_rapid.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_rapid.so.501"
  )

# Import target "opencv_reg" for configuration "Release"
set_property(TARGET opencv_reg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_reg PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_reg.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_reg.so.501"
  )

# Import target "opencv_rgbd" for configuration "Release"
set_property(TARGET opencv_rgbd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_rgbd PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_rgbd.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_rgbd.so.501"
  )

# Import target "opencv_shape" for configuration "Release"
set_property(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_shape PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_shape.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_shape.so.501"
  )

# Import target "opencv_signal" for configuration "Release"
set_property(TARGET opencv_signal APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_signal PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_signal.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_signal.so.501"
  )

# Import target "opencv_stereo" for configuration "Release"
set_property(TARGET opencv_stereo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_stereo PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_stereo.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_stereo.so.501"
  )

# Import target "opencv_surface_matching" for configuration "Release"
set_property(TARGET opencv_surface_matching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_surface_matching PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_surface_matching.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_surface_matching.so.501"
  )

# Import target "opencv_alphamat" for configuration "Release"
set_property(TARGET opencv_alphamat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_alphamat PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_alphamat.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_alphamat.so.501"
  )

# Import target "opencv_cudafilters" for configuration "Release"
set_property(TARGET opencv_cudafilters APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudafilters PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudafilters.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudafilters.so.501"
  )

# Import target "opencv_cudaimgproc" for configuration "Release"
set_property(TARGET opencv_cudaimgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaimgproc PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudaimgproc.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudaimgproc.so.501"
  )

# Import target "opencv_cudastereo" for configuration "Release"
set_property(TARGET opencv_cudastereo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudastereo PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudastereo.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudastereo.so.501"
  )

# Import target "opencv_cudawarping" for configuration "Release"
set_property(TARGET opencv_cudawarping APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudawarping PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudawarping.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudawarping.so.501"
  )

# Import target "opencv_dnn" for configuration "Release"
set_property(TARGET opencv_dnn APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_dnn.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_dnn.so.501"
  )

# Import target "opencv_dnn_superres" for configuration "Release"
set_property(TARGET opencv_dnn_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn_superres PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_dnn_superres.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_dnn_superres.so.501"
  )

# Import target "opencv_features" for configuration "Release"
set_property(TARGET opencv_features APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_features PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_features.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_features.so.501"
  )

# Import target "opencv_freetype" for configuration "Release"
set_property(TARGET opencv_freetype APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_freetype PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_freetype.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_freetype.so.501"
  )

# Import target "opencv_fuzzy" for configuration "Release"
set_property(TARGET opencv_fuzzy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_fuzzy PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_fuzzy.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_fuzzy.so.501"
  )

# Import target "opencv_hfs" for configuration "Release"
set_property(TARGET opencv_hfs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_hfs PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_hfs.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_hfs.so.501"
  )

# Import target "opencv_img_hash" for configuration "Release"
set_property(TARGET opencv_img_hash APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_img_hash PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_img_hash.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_img_hash.so.501"
  )

# Import target "opencv_imgcodecs" for configuration "Release"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "OpenEXR::OpenEXR"
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_imgcodecs.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_imgcodecs.so.501"
  )

# Import target "opencv_line_descriptor" for configuration "Release"
set_property(TARGET opencv_line_descriptor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_line_descriptor PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_line_descriptor.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_line_descriptor.so.501"
  )

# Import target "opencv_objdetect" for configuration "Release"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_objdetect.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_objdetect.so.501"
  )

# Import target "opencv_photo" for configuration "Release"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_photo.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_photo.so.501"
  )

# Import target "opencv_saliency" for configuration "Release"
set_property(TARGET opencv_saliency APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_saliency PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_saliency.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_saliency.so.501"
  )

# Import target "opencv_text" for configuration "Release"
set_property(TARGET opencv_text APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_text PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_text.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_text.so.501"
  )

# Import target "opencv_video" for configuration "Release"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_video.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_video.so.501"
  )

# Import target "opencv_videoio" for configuration "Release"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_videoio.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_videoio.so.501"
  )

# Import target "opencv_wechat_qrcode" for configuration "Release"
set_property(TARGET opencv_wechat_qrcode APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_wechat_qrcode PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_wechat_qrcode.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_wechat_qrcode.so.501"
  )

# Import target "opencv_xfeatures2d" for configuration "Release"
set_property(TARGET opencv_xfeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xfeatures2d PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_xfeatures2d.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_xfeatures2d.so.501"
  )

# Import target "opencv_ximgproc" for configuration "Release"
set_property(TARGET opencv_ximgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ximgproc PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_ximgproc.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_ximgproc.so.501"
  )

# Import target "opencv_xobjdetect" for configuration "Release"
set_property(TARGET opencv_xobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xobjdetect PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_xobjdetect.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_xobjdetect.so.501"
  )

# Import target "opencv_xphoto" for configuration "Release"
set_property(TARGET opencv_xphoto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xphoto PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_xphoto.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_xphoto.so.501"
  )

# Import target "opencv_bgsegm" for configuration "Release"
set_property(TARGET opencv_bgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_bgsegm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_bgsegm.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_bgsegm.so.501"
  )

# Import target "opencv_calib" for configuration "Release"
set_property(TARGET opencv_calib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_calib PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_calib.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_calib.so.501"
  )

# Import target "opencv_cudabgsegm" for configuration "Release"
set_property(TARGET opencv_cudabgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudabgsegm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudabgsegm.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudabgsegm.so.501"
  )

# Import target "opencv_cudacodec" for configuration "Release"
set_property(TARGET opencv_cudacodec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudacodec PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudacodec.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudacodec.so.501"
  )

# Import target "opencv_cudafeatures2d" for configuration "Release"
set_property(TARGET opencv_cudafeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudafeatures2d PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudafeatures2d.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudafeatures2d.so.501"
  )

# Import target "opencv_cudalegacy" for configuration "Release"
set_property(TARGET opencv_cudalegacy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudalegacy PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudalegacy.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudalegacy.so.501"
  )

# Import target "opencv_cudaobjdetect" for configuration "Release"
set_property(TARGET opencv_cudaobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaobjdetect PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudaobjdetect.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudaobjdetect.so.501"
  )

# Import target "opencv_datasets" for configuration "Release"
set_property(TARGET opencv_datasets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_datasets PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_datasets.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_datasets.so.501"
  )

# Import target "opencv_face" for configuration "Release"
set_property(TARGET opencv_face APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_face PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_face.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_face.so.501"
  )

# Import target "opencv_gapi" for configuration "Release"
set_property(TARGET opencv_gapi APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_gapi PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_gapi.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_gapi.so.501"
  )

# Import target "opencv_highgui" for configuration "Release"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_highgui.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_highgui.so.501"
  )

# Import target "opencv_optflow" for configuration "Release"
set_property(TARGET opencv_optflow APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_optflow PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_optflow.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_optflow.so.501"
  )

# Import target "opencv_sfm" for configuration "Release"
set_property(TARGET opencv_sfm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_sfm PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "glog::glog;gflags_shared"
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_sfm.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_sfm.so.501"
  )

# Import target "opencv.sfm.correspondence" for configuration "Release"
set_property(TARGET opencv.sfm.correspondence APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv.sfm.correspondence PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv.sfm.correspondence.a"
  )

# Import target "opencv.sfm.multiview" for configuration "Release"
set_property(TARGET opencv.sfm.multiview APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv.sfm.multiview PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv.sfm.multiview.a"
  )

# Import target "opencv.sfm.numeric" for configuration "Release"
set_property(TARGET opencv.sfm.numeric APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv.sfm.numeric PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv.sfm.numeric.a"
  )

# Import target "opencv_stitching" for configuration "Release"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_stitching.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_stitching.so.501"
  )

# Import target "opencv_structured_light" for configuration "Release"
set_property(TARGET opencv_structured_light APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_structured_light PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_structured_light.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_structured_light.so.501"
  )

# Import target "opencv_tracking" for configuration "Release"
set_property(TARGET opencv_tracking APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_tracking PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_tracking.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_tracking.so.501"
  )

# Import target "opencv_xstereo" for configuration "Release"
set_property(TARGET opencv_xstereo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xstereo PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_xstereo.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_xstereo.so.501"
  )

# Import target "opencv_bioinspired" for configuration "Release"
set_property(TARGET opencv_bioinspired APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_bioinspired PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_bioinspired.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_bioinspired.so.501"
  )

# Import target "opencv_ccalib" for configuration "Release"
set_property(TARGET opencv_ccalib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ccalib PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_ccalib.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_ccalib.so.501"
  )

# Import target "opencv_cudaoptflow" for configuration "Release"
set_property(TARGET opencv_cudaoptflow APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaoptflow PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_cudaoptflow.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_cudaoptflow.so.501"
  )

# Import target "opencv_dnn_objdetect" for configuration "Release"
set_property(TARGET opencv_dnn_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dnn_objdetect PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_dnn_objdetect.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_dnn_objdetect.so.501"
  )

# Import target "opencv_dpm" for configuration "Release"
set_property(TARGET opencv_dpm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_dpm PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_dpm.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_dpm.so.501"
  )

# Import target "opencv_superres" for configuration "Release"
set_property(TARGET opencv_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_superres PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_superres.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_superres.so.501"
  )

# Import target "opencv_videostab" for configuration "Release"
set_property(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videostab PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/nerdstar/NerdStar/backend/opencv/opencv_build/lib/libopencv_videostab.so.5.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_videostab.so.501"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
