# CMake generated Testfile for 
# Source directory: /home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudacodec
# Build directory: /home/nerdstar/NerdStar/backend/opencv/opencv_build/modules/cudacodec
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_cudacodec "/home/nerdstar/NerdStar/backend/opencv/opencv_build/bin/opencv_test_cudacodec" "--gtest_output=xml:opencv_test_cudacodec.xml")
set_tests_properties(opencv_test_cudacodec PROPERTIES  LABELS "Extra;opencv_cudacodec;Accuracy" WORKING_DIRECTORY "/home/nerdstar/NerdStar/backend/opencv/opencv_build/test-reports/accuracy" _BACKTRACE_TRIPLES "/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVUtils.cmake;1765;add_test;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1364;ocv_add_test_from_target;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudacodec/CMakeLists.txt;51;ocv_add_accuracy_tests;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudacodec/CMakeLists.txt;0;")
add_test(opencv_perf_cudacodec "/home/nerdstar/NerdStar/backend/opencv/opencv_build/bin/opencv_perf_cudacodec" "--gtest_output=xml:opencv_perf_cudacodec.xml")
set_tests_properties(opencv_perf_cudacodec PROPERTIES  LABELS "Extra;opencv_cudacodec;Performance" WORKING_DIRECTORY "/home/nerdstar/NerdStar/backend/opencv/opencv_build/test-reports/performance" _BACKTRACE_TRIPLES "/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVUtils.cmake;1765;add_test;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1263;ocv_add_test_from_target;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudacodec/CMakeLists.txt;52;ocv_add_perf_tests;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudacodec/CMakeLists.txt;0;")
add_test(opencv_sanity_cudacodec "/home/nerdstar/NerdStar/backend/opencv/opencv_build/bin/opencv_perf_cudacodec" "--gtest_output=xml:opencv_perf_cudacodec.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_cudacodec PROPERTIES  LABELS "Extra;opencv_cudacodec;Sanity" WORKING_DIRECTORY "/home/nerdstar/NerdStar/backend/opencv/opencv_build/test-reports/sanity" _BACKTRACE_TRIPLES "/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVUtils.cmake;1765;add_test;/home/nerdstar/NerdStar/backend/opencv/opencv/cmake/OpenCVModule.cmake;1264;ocv_add_test_from_target;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudacodec/CMakeLists.txt;52;ocv_add_perf_tests;/home/nerdstar/NerdStar/backend/opencv/opencv_contrib/modules/cudacodec/CMakeLists.txt;0;")
